# Generated by Django 5.0.6 on 2024-07-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_course_course_image_alter_teacher_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='video',
            name='video_number',
            field=models.IntegerField(default=1),
        ),
    ]
