# Generated by Django 5.0.6 on 2024-07-08 15:38

import teacher.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_course_course_number_video_video_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to=teacher.utils.user_directory_path),
        ),
    ]
