# Generated by Django 5.0.6 on 2024-07-10 15:03

import teacher.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to=teacher.utils.course_image_upload_path),
        ),
    ]
